# Generated by Django 3.0.2 on 2020-01-26 19:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages_plus', '0004_auto_20171214_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=False, max_length=30, unique=True, verbose_name='Method name')),
            ],
        ),
        migrations.CreateModel(
            name='SCType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='SpeedCam code name')),
                ('number', models.PositiveSmallIntegerField(unique=True, verbose_name='SpeedCam type number')),
                ('description', models.TextField(blank=True, max_length=200, verbose_name='SpeedCam description')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SCPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon', models.DecimalField(decimal_places=8, max_digits=11, verbose_name='Longitude (X)')),
                ('lat', models.DecimalField(decimal_places=8, max_digits=11, verbose_name='Latitude (Y)')),
                ('speed', models.PositiveSmallIntegerField(default=0, verbose_name='Speed limit')),
                ('dirtype', models.PositiveSmallIntegerField(default=1)),
                ('direction', models.SmallIntegerField(default=0, verbose_name='Direction from which SC catches')),
                ('danger', models.BooleanField(default=False)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('add_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date on which the SpeedCam was added')),
                ('active', models.BooleanField(default=False)),
                ('available', models.BooleanField(default=False)),
                ('method', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='TestDrive.Method', verbose_name='Method name')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestDrive.SCType', verbose_name='SpeedCam Type')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=200, verbose_name='Voice message text')),
                ('audio_file_name', models.CharField(blank=True, max_length=30)),
                ('image_file_name', models.CharField(blank=True, max_length=30)),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='languages_plus.Language')),
                ('sc_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TestDrive.SCType')),
            ],
        ),
    ]
