# Generated by Django 3.0.2 on 2020-01-24 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=30, unique=True)),
                ('voice_message_text', models.CharField(max_length=200)),
                ('audio_file_name', models.CharField(max_length=30)),
                ('image_file_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('description', models.TextField(max_length=500)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestDrive.Message')),
            ],
        ),
        migrations.CreateModel(
            name='SCPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon', models.DecimalField(decimal_places=8, max_digits=11)),
                ('lat', models.DecimalField(decimal_places=8, max_digits=11)),
                ('speed', models.PositiveSmallIntegerField(default=0)),
                ('dirtype', models.PositiveSmallIntegerField(default=1)),
                ('add_date', models.DateTimeField(verbose_name='Date on which the SpeedCam was added')),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('danger', models.BooleanField(default=False)),
                ('method', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=False)),
                ('available', models.BooleanField(default=False)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestDrive.Type')),
            ],
        ),
    ]
