# Generated by Django 3.0.2 on 2020-01-24 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestDrive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scpoint',
            name='direction',
            field=models.SmallIntegerField(default=0, verbose_name='Direction from which SC catches'),
        ),
        migrations.AlterField(
            model_name='scpoint',
            name='lat',
            field=models.DecimalField(decimal_places=8, max_digits=11, verbose_name='Latitude (Y)'),
        ),
        migrations.AlterField(
            model_name='scpoint',
            name='lon',
            field=models.DecimalField(decimal_places=8, max_digits=11, verbose_name='Longitude (X)'),
        ),
        migrations.AlterField(
            model_name='scpoint',
            name='speed',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Speed limit'),
        ),
        migrations.AlterField(
            model_name='scpoint',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestDrive.Type', verbose_name='SpeedCam Type'),
        ),
        migrations.AlterField(
            model_name='type',
            name='description',
            field=models.TextField(max_length=500, verbose_name='SpeedCam description'),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='SpeedCam code name'),
        ),
        migrations.AlterField(
            model_name='type',
            name='number',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='SpeedCam type number'),
        ),
    ]
