# Generated by Django 3.0.2 on 2020-01-24 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestDrive', '0002_auto_20200124_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=30, unique=True)),
                ('country', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestDrive.Language'),
        ),
    ]
