# Generated by Django 3.0.2 on 2020-01-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestDrive', '0003_auto_20200124_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scpoint',
            name='method',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='type',
            name='description',
            field=models.TextField(max_length=200, verbose_name='SpeedCam description'),
        ),
    ]
