# Generated by Django 3.0.2 on 2020-01-29 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestDrive', '0003_auto_20200129_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sctype',
            name='user',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
