# Generated by Django 3.0.2 on 2020-01-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestDrive', '0004_auto_20200124_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scpoint',
            name='method',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
