# Generated by Django 3.0.2 on 2020-01-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestDrive', '0005_auto_20200124_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scpoint',
            name='lat',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=11, verbose_name='Latitude (Y)'),
        ),
        migrations.AlterField(
            model_name='scpoint',
            name='lon',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=11, verbose_name='Longitude (X)'),
        ),
    ]
