# Generated by Django 3.0.2 on 2020-01-24 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestDrive', '0007_auto_20200124_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=False, max_length=30, unique=True, verbose_name='Method name')),
            ],
        ),
        migrations.AlterField(
            model_name='scpoint',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestDrive.Method', verbose_name='Method name'),
        ),
    ]
