# Generated by Django 3.0.2 on 2020-01-24 19:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TestDrive', '0008_auto_20200124_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='alpha3',
            field=models.CharField(blank=True, max_length=3, null=True, unique=True, verbose_name='Short language name'),
        ),
        migrations.AlterField(
            model_name='language',
            name='country',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Language name'),
        ),
        migrations.AlterField(
            model_name='message',
            name='audio_file_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='message',
            name='image_file_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='scpoint',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 24, 19, 58, 43, 947530, tzinfo=utc), verbose_name='Date on which the SpeedCam was added'),
        ),
        migrations.AlterField(
            model_name='scpoint',
            name='lat',
            field=models.DecimalField(decimal_places=8, max_digits=11, verbose_name='Latitude (Y)'),
        ),
        migrations.AlterField(
            model_name='scpoint',
            name='lon',
            field=models.DecimalField(decimal_places=8, max_digits=11, verbose_name='Longitude (X)'),
        ),
        migrations.AlterField(
            model_name='scpoint',
            name='method',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='TestDrive.Method', verbose_name='Method name'),
        ),
        migrations.AlterField(
            model_name='type',
            name='description',
            field=models.TextField(blank=True, max_length=200, verbose_name='SpeedCam description'),
        ),
        migrations.AlterField(
            model_name='type',
            name='message',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='TestDrive.Message'),
        ),
    ]
