# Generated by Django 3.0.2 on 2020-01-24 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestDrive', '0010_auto_20200124_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='alpha3',
            field=models.CharField(max_length=3, null=True, unique=True, verbose_name='Short language name'),
        ),
    ]
