# Generated by Django 3.0.2 on 2020-01-24 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestDrive', '0011_auto_20200124_2307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='alpha3',
            new_name='alpha_3',
        ),
    ]
